export const FETCHING_DATA_QUESTION = 'FETCHING_DATA_QUESTION';
export const FETCHING_DATA_QUESTION_SUCCESS = 'FETCHING_DATA_QUESTION_SUCCESS';
export const FETCHING_DATA_QUESTION_FAILURE = 'FETCHING_DATA_QUESTION_FAILURE';
export const SELECT_OPTION = 'SELECT_OPTION';
export const CHECKING_ANSWER = 'CHECKING_ANSWER';
export const CHECKING_ANSWER_SUCCESS = 'CHECKING_ANSWER_SUCCESS';
export const CHECKING_ANSWER_FAILURE = 'CHECKING_ANSWER_FAILURE';
